<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>bandit.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bandit.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DiscUtils.Core" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Fat" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Streams" Version="0.16.13" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

</Project>
