<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>BadBuilder</AssemblyName>
    <RootNamespace>BadBuilder</RootNamespace>
    <Version>2.1.0</Version>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscUtils.Core" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Fat" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Raw" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Streams" Version="0.16.13" />
    <PackageReference Include="Octokit" Version="13.0.1" />
    <PackageReference Include="SharpCompress" Version="0.38.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
